name: Tests executer

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Run tests.sh
      - name: Tests execute
        run: |
          ./tests.sh 

      # Upload feedback
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: tests-execute
          path: ./test-results.txt
