name: Tests Executer

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  tests-executer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pandas sqlite3

      # Run tests.sh
      - name: Tests execute
        run: |
          chmod +x ./tests.sh
          ./tests.sh